language: python
python:
  - "2.7"
env:
  matrix:
    - DB=sqlite
    - DB=mysql
    - DB=postgres
# command to install dependencies
install:
  - pip install -r requirements.txt
  - if [ $DB == 'postgres' ]; then pip install -q psycopg2 ; fi
  - if [ $DB == 'mysql' ]; then pip install -q mysql-python ; fi
before_script:
  - if [ $DB == 'postgres' ]; then psql -c 'create database treeio;' -U postgres ; fi
  - if [ $DB == 'mysql' ]; then mysql -e 'create database treeio;' ; fi
  -
  -
# command to run tests
script: python manage.py test